---
version: "2"
services:
  plexrequests:
    image: lokenx/plexrequests-meteor
    container_name: plexrequests
    restart: unless-stopped
    ports:
     - ${PORT}:80
    depends_on:
     - mongo
    environment:
     - MONGO_URL=mongodb://mongo:27017/plexrequests
     - ROOT_URL=http://localhost/
     - PUID=${PUID}
     - PGID=${PGID}
    volumes:
     - /portainer/Files/AppData/Config/PlexRequests:/config

  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - /portainer/Files/AppData/Config/PlexRequests/DB:/data/db